robot:
  type: "Franka"
  tip_offset: [0.0, 0.0, 0.15]
  ik_params:
    lambda_val: 0.01
  step_size: 0.05
  noise_std: 0.00001

env:
  num_envs: 4
  fps: 15
  spacing: 15.0
  obj_names: ["sphere01", "sphere02"]
  stabilize_steps: 10
  hold_steps: 5
  eps: 0.015
  episode_length_s: 10

task:
  id: "Drop_Two_Spheres"
  sequence: ["drop"]
  physical_property: "restitution"

data:
  repo_id: "mlcf-robot/drop_spheres_vqa_dataset"
  num_episodes: 8
  video_keys:
    [
      "cam_front_narrow",
      "cam_front_wide",
      "cam_front_left_narrow",
      "cam_front_right_narrow",
      "cam_back_narrow",
      "cam_back_left_narrow",
      "cam_back_right_narrow",
    ]
  vcodec: "h264_nvenc"
