robot:
  type: "Franka"
  tip_offset: [0.0, 0.0, 0.15]
  ik_params:
    lambda_val: 0.01
  step_size: 0.1
  noise_std: 0.00001

env:
  num_envs: 2
  fps: 15
  spacing: 15.0
  obj_names: ["cylinder01", "cylinder02"]
  stabilize_steps: 20
  hold_steps: 10
  eps: 0.001
  episode_length_s: 9

task:
  id: "Push_Two_Cylinders"
  sequence: ["push"]
  physical_property: "mass"

data:
  repo_id: "mlcf-robot/push_cylinders_vqa_dataset"
  num_episodes: 4
  video_keys:
    [
      "cam_front_top_narrow",
      "cam_back_top_narrow",
      "cam_back_wide",
      "cam_back_left_wide",
      "cam_back_right_wide",
      "cam_front_left_narrow",
      "cam_front_right_narrow",
    ]
  vcodec: "h264_nvenc"
